import Nav from '../components/nav/nav';
import SideBar from '../components/sideBar/sideBar';
import './home.css';

function Home(){
    return(
        <div className="home">
            <Nav></Nav>
            <SideBar></SideBar>
            <h2>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa molestias earum dolor repellendus nostrum non sint iusto tempora nemo veritatis, itaque, ex, totam doloremque possimus labore optio molestiae eaque. Odio, illum recusandae facilis dolore enim aspernatur non ex pariatur id, veritatis a accusamus nemo quam quibusdam tempora eius cupiditate. Ut illum veniam, at necessitatibus commodi esse maiores adipisci praesentium obcaecati, laboriosam quas, eaque voluptatum ratione maxime explicabo aliquam rerum? Placeat commodi vitae tempore, odio laudantium pariatur voluptatibus consequatur consequuntur sapiente libero, quam delectus odit explicabo labore quos dicta cumque perspiciatis voluptate sunt
         ducimus nisi corporis asperiores! Illum quis culpa omnis accusamus suscipit aspernatur et repudiandae assumenda voluptatem distinctio natus quibusdam, tempora hic! Aliquam tempora nemo quisquam, reiciendis est saepe accusamus ullam corporis libero nobis facilis, distinctio voluptatibus blanditiis mollitia. Id officiis dicta, optio corrupti repudiandae veniam doloremque, exercitationem saepe expedita nihil quos maiores corporis dolores delectus obcaecati iure neque aliquam modi vel! Ullam in consequuntur earum. Accusamus asperiores ullam laudantium aperiam, dignissimos quia excepturi sed vero suscipit sunt magni quam nesciunt, eveniet iure recusandae maiores. Adipisci quia soluta sint voluptate! Eaque temporibus eveniet, cupiditate illum quia repudiandae quidem quod id cumque, ut consequuntur reprehenderit deleniti doloribus qui fuga soluta expedita delectus. In, impedit. Quaerat
          architecto nostrum quisquam ut enim repudiandae amet sunt, a nemo temporibus aliquid quod alias veritatis placeat sapiente quo cumque. Tenetur sunt maiores dolor vel vero quisquam cumque! Dolorum eveniet minus nihil vel, aspernatur aut cupiditate. Tenetur esse rerum tempora illo dolorem corrupti, quaerat laborum sunt dolore cupiditate sequi non quod aperiam necessitatibus quisquam odit quidem minus quam placeat nihil! Deleniti perspiciatis cum rem magnam quo dolore fugit iure, sint ab temporibus natus nostrum iste corporis vitae numquam reiciendis! Natus itaque laborum quidem ipsam architecto tenetur aut corporis, ut id sint aspernatur esse repellat earum voluptas autem dolore odio tempora sed. Et deleniti cum necessitatibus totam excepturi labore, dignissimos incidunt magnam perspiciatis illum iste ea temporibus modi pariatur aliquid esse culpa quo, ut assumenda nam odio ducimus. Incidunt quam assumenda voluptatum id nam, quidem consequatur officia enim perspiciatis, in qui doloribus fugiat facilis labore quasi perferendis vero voluptas maiores? Modi, illum ratione? Expedita eveniet omnis veniam optio iure ducimus non sed nisi esse deleniti voluptas, distinctio po
          rro aspernatur molestias numquam provident architecto quisquam quis quidem reiciendis fugiat eius dolor hic. Mollitia iste quibusdam pariatur, non animi, consequatur fuga omnis quas aut ipsa placeat vitae exercitationem aperiam dicta labore consectetur! Odit deleniti vitae a ad exercitationem, repellendus alias voluptas est ab ratione. Ipsa facere eveniet facilis rerum illum cumque voluptatem recusandae quo suscipit numquam, dolores ab, voluptates quia debitis cum aperiam quidem hic est dolore corrupti blanditiis. Unde dolore blanditiis natus inventore ipsa amet nisi quaerat laborum, ducimus, reprehenderit nesciunt accusamus! Iure quas eligendi nisi recusandae, enim illo consequuntur consectetur libero hic rerum fuga amet, cumque odit laborum! Maiores porro, pariatur nobis, unde iusto atque
           quibusdam voluptates eveniet, fuga fugit ratione itaque asperiores accusantium? A repellendus inventore cum enim quidem totam! Reprehenderit, quaerat tenetur sint hic est assumenda doloribus. Sit soluta provident odit placeat molestias, impedit, pariatur unde facere architecto dolorum commodi numquam. A obcaecati ipsam, minus consequuntur eveniet amet nostrum aspernatur quod nihil ut tempore molestiae, alias fugiat, culpa quibusdam dolor? Iste vero debitis voluptates magnam, ab rem earum esse aperiam nemo odio sequi rerum iure sapiente non alias explicabo consequatur voluptatem ipsam fugit odit accusantium quia sint blanditiis. Dicta consequatur maxime magnam laboriosam tempora voluptatibus cumque natus nihil provident beatae rerum officiis minus, totam, voluptatum quaerat eos, accusantium magni consequuntur ullam vitae? Inventore quod consequatur laborum minus, omnis ad ut vel repellendus officia nam cum, voluptatibus quas nulla totam ipsa reprehenderit, 
           veritatis sed iste delectus sint. Distinctio, esse ex. Eligendi velit eveniet rem quis id ducimus consequatur enim impedit quasi vel earum ipsam inventore facere asperiores, a doloribus saepe natus amet possimus qui reprehenderit sapiente error perspiciatis. Soluta totam atque, eum molestiae consequatur repudiandae voluptatibus molestias laudantium temporibus natus. Perspiciatis ut velit quam nulla vitae, dignissimos labore soluta architecto inventore dolorum rem porro error rerum placeat. Exercitationem asperiores beatae atque magni cumque ratione, voluptate esse libero illo quaerat maiores culpa quidem natus, consequuntur ex adipisci quis eum, sapiente iure obcaecati facere. Quis ipsa possimus, eius natus inventore incidunt voluptatem repellat commodi mollitia quaerat consequatur
            harum, suscipit obcaecati consectetur a nesciunt eum blanditiis distinctio, autem sed molestias molestiae fuga illo? Impedit ipsa aliquam ullam dolorem dicta quidem molestiae quasi necessitatibus placeat velit natus culpa libero, maxime reiciendis laudantium fugiat ab quibusdam fugit. Nostrum saepe culpa quo soluta voluptates, ducimus excepturi molestias, doloremque rem incidunt itaque eius unde officiis autem neque corporis. Corrupti, in maiores vitae quo fugit adipisci officiis, delectus perferendis quas quae consequatur culpa possimus perspiciatis amet suscipit totam placeat distinctio minima quidem. Voluptatibus reiciendis a voluptas aliquid doloremque magnam fuga, illum, numquam placeat quasi, unde hic et suscipit. Alias tempore itaque aperiam eos necessitatibus asperiores possimus, omnis cupiditate, laborum corporis ex nisi veniam sapiente ab similique quo, quia deleniti. Repudiandae commodi fugiat, quae facere expedita enim tempora voluptates asperiores 
            eveniet ipsam adipisci, distinctio, repellendus quo aliquid nisi assumenda exercitationem hic amet odio temporibus libero esse? Nihil atque, eaque nobis odit necessitatibus ea, obcaecati commodi corrupti quam repudiandae dolores sit corporis amet nesciunt laborum! Debitis ducimus beatae dicta aliquid a explicabo, quisquam, rerum, itaque molestias est illum incidunt. Laudantium eveniet rerum rem, quas doloremque alias architecto assumenda, nemo veniam iure eos ut quis unde quam aperiam doloribus dolorum quidem? Repellat cumque iure ex possimus! Laboriosam labore quis sequi laudantium veritatis est quidem itaque. Nihil minima laboriosam tempora tenetur voluptatem delectus beatae id aliquid 
            nostrum autem. Perferendis voluptate quia tempora distinctio officiis quaerat recusandae delectus sint pariatur, placeat quo ipsam eaque, sunt quam ex? Omnis quaerat autem neque laborum recusandae repellat reprehenderit possimus, velit magnam sunt, dicta voluptatem reiciendis ea perspiciatis? Perspiciatis quod dicta rem. Quaerat soluta ipsum repellendus veniam error non aut magnam sequi nam! Aliquid id consequuntur rem facere sequi alias temporibus, quae provident fuga! Cupiditate ad amet modi aliquam nesciunt saepe. Voluptatum, aperiam sed.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum architecto explicabo placeat laboriosam maiores doloremque dolorem assumenda labore modi id officia saepe et, incidunt sapiente quae. Ea ratione mollitia a reprehenderit nam. Consequatur inventore possimus praesentium expedita non porro, impedit accusantium. Accusamus quis vero laudantium. Ullam sunt id dolorum nisi explicabo. Inventore fuga odio consequatur assumenda quaerat cupiditate reprehenderit aspernatur accusamus. Quia, voluptas porro dolor quas repellat, aliquam aliquid ullam quod libero nihil eum reprehenderit laudantium illum aut odio ipsa perferendis quasi officia accusamus sed dolorem. Doloribus natus fugiat soluta iste aliquam odio dolorum fugit eius perferendis, placeat quidem! Enim dolores fugiat nam velit minima culpa dignissimos maiores expedita voluptatem perferendis accusantium, mollitia ex doloremque aliquid animi eos reiciendis iste cumque. Itaque ut amet quo, vitae veritatis quam commodi enim tenetur impedit doloremque debitis sit ducimus sint rerum corrupti ea nisi est ab odit voluptas. Quas in aspernatur voluptatibus temporibus aperiam deleniti harum corporis, blanditiis sunt laudantium provident exercitationem voluptatem atque libero nisi ratione debitis aliquid porro ipsam? Illo optio, consequuntur nesciunt error quibusdam eveniet! Temporibus vitae quo at eius consequatur corporis, reprehenderit necessitatibus aliquam optio maxime obcaecati doloribus, officiis tempore corrupti libero est veritatis? Velit nostrum debitis totam pariatur!
        </h2>
        
        </div> 
    );
}

export default Home;